// <auto-generated />
namespace BestCaseHotNews.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class foobar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foobar));
        
        string IMigrationMetadata.Id
        {
            get { return "201402262026531_foobar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
