// <auto-generated />
namespace BestCaseHotNews.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PassWordFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PassWordFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201402252136295_PassWordFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
